#!/bin/bash

HOME=$OPENSHIFT_REPO_DIR
cd $OPENSHIFT_REPO_DIR

mkdir -p "$OPENSHIFT_DATA_DIR"node_modules
mkdir -p "$OPENSHIFT_DATA_DIR"bower_components

ln -s "$OPENSHIFT_DATA_DIR"node_modules node_modules
ln -s "$OPENSHIFT_DATA_DIR"bower_components client/bower_components

npm install
bower install
grunt build

ls -1 | grep -E -v 'dist|node_modules|.tmp' | xargs rm -rf
mv dist/* .
rm -rf dist

export NODE_ENV="production"
