#!/bin/bash

# Change home directory (bower puts a lot of cache and tmp directories here)
HOME=$OPENSHIFT_REPO_DIR
cd $OPENSHIFT_REPO_DIR

# add ruby gems to path (will not persist)
export PATH=`gem environment gemdir`/bin:$PATH
# install sass
gem install sass --no-ri --no-rdoc

mkdir -p "$OPENSHIFT_DATA_DIR"node_modules
mkdir -p "$OPENSHIFT_DATA_DIR"bower_components

ln -s "$OPENSHIFT_DATA_DIR"node_modules node_modules
ln -s "$OPENSHIFT_DATA_DIR"bower_components client/bower_components

npm install --loglevel error

# Prune unused node node_modules
npm prune
# Prune some unecessary files from node_modules
find node_modules/* -type f -iname "*.md" -o -type d -name "test*" -o -type d -name "example*" | xargs rm -rf

bower install -q
grunt build

ls -1 | grep -E -v 'dist|node_modules' | xargs rm -rf
mv dist/* .
rm -rf dist
